Feature/initial server api
rtatarinov/investements-kotlin pull request #2
Opened 2021-04-12 16:00 UTC by rtatarinov

2021-04-12 16:20 UTC, artem328 approved these changes

2021-04-15 09:18 UTC, rtatarinov commented on src/jvmMain/kotlin/com/investments/httpapi/domain/category/Category.kt
> +    @Serializable(with = UUIDSerializer::class)
Мне очень не нравится, что я классу прибавляю `Serializer` да еще по сути их сторонней библиотеки
Это прям совсем не чисто выходит. Моя бизнес логика выходит подстраивается под ответ, который я клиенту должен отправить. Но я хз, как это сделать правильно

2021-04-15 09:19 UTC, rtatarinov commented on src/jvmMain/kotlin/com/investments/httpapi/domain/category/Category.kt
> +    }
Добавил для метода `patch`, но мне тоже это не нравится. 
Я тут почитал, и в моем понимании это должен быть просто `data class` здесь, потому что он не содержит ничего кроме данных. Я не уверен, что сеттер тут вообще должен быть.

2021-04-15 09:21 UTC, rtatarinov commented on src/jvmMain/kotlin/com/investments/httpapi/domain/routes/CategoriesRoutes.kt
> +        }
В постмане этот запрос возвращает 500 без какой-либо информации
Как дебажить такие вещи?

2021-04-15 09:24 UTC, rtatarinov commented on src/jvmMain/kotlin/com/investments/httpapi/domain/routes/CategoriesRoutes.kt
> +            val payload = call.receive<Category>()
Вот тут вообще больная тема. Я ему говорю, что я жду здесь payload с типом Category.
Но это неправда. Я жду здесь `partial Category`, этого нет в котлине, в отличии от TS.
Но, возможно, и скорее всего так и должно быть. Пэйлоад в принципе у меня не должен соответствовать классу, потому что не могу гарантировать, что клиент отправит данные соответствующие нужному классу (даже частично)

Тогда здесь должно быть `Any`. И встает вопрос, как это вообще правильно обрабатывать

2021-04-19 07:38 UTC, artem328 commented on src/jvmMain/kotlin/com/investments/httpapi/domain/category/Category.kt
> +    @Serializable(with = UUIDSerializer::class)
Это лучше вынести в отдельный DTO для view (поля могут дублироваться, но назначение классов разное). Этот хранит бизнесовые данные, а вьюшка просто описывает что отдается клиенту, чисто данные без логики

2021-04-19 07:38 UTC, artem328 commented on src/jvmMain/kotlin/com/investments/httpapi/domain/category/CategoryRepository.kt
> +    fun add(item: Category)
Предлагаю переименовать в save, метод который должен персистить данные, независимо от того есть они в репе или нет. (если нет, то создать, если есть, то обновить)

2021-04-19 07:38 UTC, artem328 commented on src/jvmMain/kotlin/com/investments/httpapi/domain/category/CategoryRepository.kt
> +    fun findIndexById(id: String): Int
специфичный метод для списка, в репозитории не нужен

2021-04-19 07:38 UTC, artem328 commented on src/jvmMain/kotlin/com/investments/httpapi/domain/category/CategoryRepository.kt
> +    fun updateItemById(id: String, payload: Category): Category?
с методом save данный метод не нужен

2021-04-19 07:38 UTC, artem328 commented on src/jvmMain/kotlin/com/investments/httpapi/domain/routes/CategoriesRoutes.kt
> +                call.respond(categories.getAll())
здесь нужно будет трансформировать модели во вьюшки
```
val categories = categories.getAll()
val view = viewFactory.createFromList(categories) // returns category list dto
call.respond(view)
```

2021-04-19 07:38 UTC, artem328 commented on src/jvmMain/kotlin/com/investments/httpapi/domain/routes/CategoriesRoutes.kt
> +        }
тебе нужно не Category получать, а какой-то dto типа CreateCategoryRequest, в котором описаны все поля которые ты теоритически принимаешь (обязательные и опциональные). После этого  с помощью какого-то сервиса из реквеста можно создать Category и его уже сохранить в репу. DTO может иметь не валидные данные и должен валидироваться, чтобы сущность создавалсь только валидная.

2021-04-19 07:38 UTC, artem328 commented on src/jvmMain/kotlin/com/investments/httpapi/domain/routes/CategoriesRoutes.kt
> +            val payload = call.receive<Category>()
Такая же история как с созданием, только реквест на редактирование, и обновление сущности который ты должен достать из репы по id

2021-04-19 07:38 UTC, artem328 commented on src/jvmMain/kotlin/com/investments/httpapi/domain/category/CategoryRepository.kt
> +    fun removeById(id: String)
достаточно метода `remove(category: Category)`

2021-04-19 07:38 UTC, artem328 commented on src/jvmMain/kotlin/com/investments/httpapi/domain/category/MemoryCategoryRepository.kt
> +    private val items = initialCategories;
в данном случае лучше создать копию, чтобы сслыка на items не вела на тот же объект листа, который пришел из вне. Иначе получается что у тебя можно поменять список снаружи

2021-04-20 12:21 UTC, artem328 requested changes

2021-04-20 12:21 UTC, artem328 commented on src/jvmMain/kotlin/com/investments/httpapi/domain/category/MemoryCategoryRepository.kt
> +            this.updateItemById(category.getId().toString(), category)
это не имеет смысла. save при обновлении вообще ничего не должен делать в данном случае, так как данные объека уже будут обновлены в самом объекте

2021-04-20 12:21 UTC, artem328 commented on src/jvmMain/kotlin/com/investments/httpapi/domain/category/request/CategoryRequest.kt
> +class CategoryRequest(
это должен быть data class наверное, в любом случае довольно странно что у тебя этот класс создает сущность категории

2021-04-26 08:57 UTC, artem328 requested changes

2021-04-26 08:57 UTC, artem328 commented on src/jvmMain/kotlin/com/investments/httpapi/config/ManualConfig.kt
> +    fun getCategoryModule(): Module {
а в чем сакральный смысл? Это же лишний метод

2021-04-26 08:57 UTC, artem328 commented on src/jvmMain/kotlin/com/investments/httpapi/domain/category/factory/CategoryViewFactory.kt
> +            CategoryView(it.name, it.id)
`createSingle(it)`

2021-04-26 08:57 UTC, artem328 commented on src/jvmMain/kotlin/com/investments/httpapi/domain/entity/Category.kt
> +    fun replaceWith(updatedCategory: Category) {
странное решение. для патча не нужно создавать новую категорию и потом обновлять ее новой сущностью. У тебя есть DTO для этого. Ты можешь создать сервис или прям в контролере менять название категории из RequestDTO

2021-04-26 08:57 UTC, artem328 commented on src/jvmMain/kotlin/com/investments/httpapi/routes/CategoriesRoutes.kt
> +            val category = CategoryFactory().create(categoryRequest)
CategoryFactory надо бы так же инжектнуть

2021-04-26 08:57 UTC, artem328 commented on src/jvmMain/kotlin/com/investments/httpapi/routes/CategoriesRoutes.kt
> +            val categoryRequest = CategoryRequest(payload.name)
а ты разве не получаешь payload типа CategoryRequest? зачем его руками создаешь?

2021-04-26 08:57 UTC, artem328 commented on src/jvmMain/kotlin/com/investments/httpapi/routes/CategoriesRoutes.kt
> +                call.respond(status = HttpStatusCode.Accepted, categoryView)
почему решил accepted, здесь 200 подойдет. 202 это для асинхроных операций https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/202

2021-04-26 08:57 UTC, artem328 commented on src/jvmMain/kotlin/com/investments/httpapi/routes/CategoriesRoutes.kt
> +            if (category != null) {
для чистоты я бы сделал 

```kotlin
if (category == null) {
   return@patch call.respondText(
                    "Category with this id doesn't exists",
                    status = HttpStatusCode.NotFound
                )
}

// logic
```

2021-04-26 08:57 UTC, artem328 commented on src/jvmMain/kotlin/com/investments/httpapi/routes/CategoriesRoutes.kt
> +                category.replaceWith(updatedCategory)
про это написал в самом классе категории

2021-04-26 08:57 UTC, artem328 commented on src/jvmMain/kotlin/com/investments/httpapi/routes/CategoriesRoutes.kt
> +            val categoryView = CategoryViewFactory().createSingle(category)
CategoryViewFactory тоже нужно инжектнуть

2021-04-26 08:57 UTC, artem328 commented on src/jvmMain/kotlin/com/investments/httpapi/routes/CategoriesRoutes.kt
> +            if (category != null) {
тоже можно использовать early return

2021-04-26 15:55 UTC, rtatarinov commented on src/jvmMain/kotlin/com/investments/httpapi/routes/CategoriesRoutes.kt
> +            val categoryRequest = CategoryRequest(payload.name)
излишне, да

2021-04-26 15:57 UTC, rtatarinov commented on src/jvmMain/kotlin/com/investments/httpapi/routes/CategoriesRoutes.kt
> +            val category = CategoryFactory().create(categoryRequest)
зачем? чем это поможет? Это же работа с самой логикой. Она не будет подменяться

2021-05-02 11:02 UTC, merged