Feature/add validation
rtatarinov/investements-kotlin pull request #3
Opened 2021-05-02 12:59 UTC by rtatarinov

2021-05-11 11:03 UTC, artem328 requested changes

2021-05-11 11:03 UTC, artem328 commented on src/jvmMain/kotlin/com/investments/httpapi/api/errors/exceptions/InvalidException.kt
> +class InvalidException(private val errors: List<Error>) : ApiException() {
название мало о чем говорит. Invalid что?

2021-05-11 11:03 UTC, artem328 commented on src/jvmMain/kotlin/com/investments/httpapi/category/factory/CategoryFactory.kt
> +class CategoryFactory : CategoryFactory {
а так можно CategoryFactory наследуют CategoryFactory?

2021-05-11 11:03 UTC, artem328 commented on src/jvmMain/kotlin/com/investments/httpapi/category/factory/CategoryViewFactory.kt
> +class CategoryViewFactory : CategoryViewFactory {
и тут?

2021-05-26 12:08 UTC, rtatarinov commented on src/jvmMain/kotlin/com/investments/httpapi/category/factory/CategoryFactory.kt
> +class CategoryFactory : CategoryFactory {
А он не наследует, он реализует интерфейс

2021-05-26 12:08 UTC, merged